# Generated by Django 5.0.7 on 2025-08-17 21:19

import core.models
import core.utils
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_learningresource'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learningresource',
            name='content',
            field=models.TextField(blank=True, help_text='Main content for articles/tutorials'),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='document',
            field=models.FileField(blank=True, help_text='Upload PDF document (max 10MB)', null=True, upload_to=core.models.learning_resource_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='document_text',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='resource_type',
            field=models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('pdf', 'PDF Document'), ('tutorial', 'Tutorial')], default='article', max_length=20),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='video_embed_code',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL to video content (YouTube, Vimeo, etc.)', null=True, validators=[core.utils.validate_video_url]),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='image',
            field=models.ImageField(blank=True, help_text='Cover image for the resource', null=True, upload_to='learning_resources/covers/'),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='view_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='learningresource',
            index=models.Index(fields=['status', 'published_at'], name='core_learni_status_614ef6_idx'),
        ),
        migrations.AddIndex(
            model_name='learningresource',
            index=models.Index(fields=['resource_type', 'status'], name='core_learni_resourc_5f3bae_idx'),
        ),
    ]
