# Generated by Django 5.0.7 on 2025-08-26 07:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='bi-folder', help_text='Bootstrap icon class', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Template Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField()),
                ('template_type', models.CharField(choices=[('landing', 'Landing Page'), ('portfolio', 'Portfolio'), ('business', 'Business'), ('blog', 'Blog'), ('ecommerce', 'E-commerce'), ('dashboard', 'Dashboard'), ('app', 'Web App'), ('other', 'Other')], default='other', max_length=20)),
                ('github_url', models.URLField(help_text='GitHub repository URL')),
                ('github_pages_url', models.URLField(blank=True, help_text='GitHub Pages live demo URL')),
                ('technologies', models.CharField(help_text='Technologies used (e.g., HTML, CSS, JavaScript, React)', max_length=300)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='templates/thumbnails/')),
                ('preview_images', models.JSONField(blank=True, default=list, help_text='List of preview image URLs')),
                ('author', models.CharField(blank=True, max_length=100)),
                ('license_type', models.CharField(default='MIT', max_length=50)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=300)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='website_templates.templatecategory')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_featured', 'is_active'], name='website_tem_is_feat_cf224b_idx'), models.Index(fields=['category', 'template_type'], name='website_tem_categor_152b7e_idx')],
            },
        ),
    ]
