# Generated by Django 5.0.7 on 2025-08-22 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding_challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenge',
            options={'verbose_name': 'Code Challenge', 'verbose_name_plural': 'Code Challenges'},
        ),
    ]
