# Generated by Django 5.0.7 on 2025-08-26 06:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_alter_challenge_options_course_curriculum_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='course',
            name='duration_hours',
            field=models.PositiveIntegerField(default=0, help_text='Estimated course duration in hours'),
        ),
        migrations.AddField(
            model_name='course',
            name='featured',
            field=models.BooleanField(default=False, help_text='Featured course'),
        ),
        migrations.AddField(
            model_name='course',
            name='learning_outcomes',
            field=models.TextField(blank=True, help_text='What students will learn'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.TextField(blank=True, help_text='Course prerequisites'),
        ),
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.CharField(blank=True, help_text='Brief course summary', max_length=300),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, help_text='Years of teaching/industry experience'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='expertise',
            field=models.CharField(blank=True, help_text='Areas of expertise (comma-separated)', max_length=200),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Verified instructor status'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='website_url',
            field=models.URLField(blank=True, help_text='Personal/professional website'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Lesson duration in minutes'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_preview',
            field=models.BooleanField(default=False, help_text='Allow preview without enrollment'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('video', 'Video'), ('text', 'Text/Reading'), ('quiz', 'Quiz'), ('assignment', 'Assignment')], default='video', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='lesson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Brief description about the instructor'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, help_text='Lesson content/description'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube, Vimeo, or direct video URL'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('course', 'order')},
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status', 'featured'], name='lms_course_status_890e4e_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category', 'difficulty'], name='lms_course_categor_04d964_idx'),
        ),
    ]
