# Generated by Django 5.0.7 on 2025-08-26 06:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_alter_course_options_course_duration_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Module title (e.g., 'Introduction to Python')", max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('description', models.TextField(blank=True, help_text='Brief description of what this module covers')),
                ('order', models.PositiveIntegerField(default=1, help_text='Order within the course')),
                ('duration_minutes', models.PositiveIntegerField(default=0, help_text='Estimated module duration in minutes')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='lms.course')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['order'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('course', 'order')},
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(blank=True, help_text='Optional: Organize lesson into a module', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lms.module'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('course', 'order'), ('module', 'order')},
        ),
    ]
